<?php
require('local_config.php');
require('../../lib/classSherport.php');

$tstart = $zeit_start = microtime(true); // current time

$serverName = $_SERVER['SERVER_NAME'];
$serverPath = dirname($_SERVER['SCRIPT_NAME']);
$serverSecure = isset($_SERVER['HTTPS']);
session_name($GLOBALS['config']['website']['cookieName']);
session_set_cookie_params(0, $serverPath, $serverName, $serverSecure, true);
session_start();

// create the sherport-object
$sherport = new classSherport();
global $html, $javafile, $javascript;
$payData = array(
	'articles' => array(
		array('amount' => 2, 'article' => 'Qualle Furioso Red', 'price' => 1189, 'tax' => 1900),
		array('amount' => 1, 'article' => 'Aquarium Plexiglas Rund', 'price' => 4900, 'tax' => 1900),
		array('amount' => 5, 'article' => 'Quallo Deluxe 500gr Packung', 'price' => 349, 'tax' => 700),
	),
	'sum' => 9023,
	'currency' => 'EUR',
);
$fetchData = array(
	'req' => array('namePerson', 'address.shipping', 'address.billing.sameAsShipping'),
	'opt' => array('contact.email', 'contact.phone'),
);

// check if user pressed the logout-button
if (!empty($_POST['logout'])) {
	unset($_SESSION['loggedIn']);
}
// check if this pageview is a payment attemp
if (!empty($_GET['t'])) {
	// import the stored login-token.
	// We need to use the token from the last call to paymentInit, because the qr-code is connected to it
	$sherport->importTokenArray($_SESSION['token']);
	if ($userData = $sherport->paymentGetData($_GET['t'])) {
		$_SESSION['userData'] = $userData;
/*		if ($userData['id-anonym']) {
			$_SESSION['loggedIn'] = true;
		}
*/	}
}
$title = 'Sherport Example 3 - Internet payment';
$step = isset($_REQUEST['step'])? intval($_REQUEST['step']): 0;
$html = '<div class="verlauf clearfix">
	<div class="hell">Warenkorb</div>
	<div'.(($step > 0)? ' class="hell"': '').'>Anmelden</div>
	<div'.(($step > 1)? ' class="hell"': '').'>Registrieren</div>
	<div'.(($step > 2)? ' class="hell"': '').'>Adresse</div>
	<div'.(($step > 3)? ' class="hell"': '').'>Bezahlen</div>
	<div'.(($step > 4)? ' class="hell"': '').'>Bestätigen</div>
</div>';
switch ($step) {
	// What to show
	case 1:
		// step 2: display of the qr-code
		unset($_SESSION['token']);
		// At first, create payment data for the token
		// import all three articles from the $payData-Array above
		// In a real shop you would get this data from a database
		foreach ($payData['articles'] as $article) {
			$sherport->addArticle($article['amount'], $article['article'], $article['price'], false, $article['tax']);
		}
		// additional shipping cost
		switch($_POST['versand']) {
			case 'dhl': $company = 'DHL'; $sum = 100; break;
			case 'hermes': $company = 'Hermes'; $sum = 150; break;
			case 'nn': $company = 'Nachnahme'; $sum = 200; break;
		}
		// because the shipping infos should not displayed in the article-list, we add it here with addOther
		$sherport->addOther('shipping', $sum, 1900, $company);

		// Now create a payment token
		// We set here an option for the payment
		// double confirmation here means that a press on the pay-button in sherport is not the final confirmation for the payment.
		// Instead the browser of the shop is redirected to a payment confirmation page where the user can view all payment details
		// and he can accept or cancel the payment on the website of the shop
		$options = array('doubleConfirm' => TRUE);
		if ($sherport->paymentInit($GLOBALS['config']['sherport']['consumerId'], $fetchData, null, $options)) {
			// paymentInit created a token which needs to be accessed after a page reload
			// so we need to store it somewhere
			$_SESSION['token'] = $sherport->exportTokenArray();
		}

		// Include the sherport-javascript in the page header
		$javafile = $sherport->getJsLibHtml();

		// We must configure the sherport-javascript
		// token: the token which was generated by loginInit
		// urlSuccess: the url to which our webpage will be redirected on successful login
		$javascript = 'var sherportConfig={token: "'.$sherport->getToken().'", urlSuccess: "'.($serverSecure? 'https://': 'http://').$serverName.$serverPath.'/index.php?step=5", urlCancel: "'.($serverSecure? 'https://': 'http://').$serverName.$serverPath.'/index.php"};';

		// The page html of step 2
		// the html for display of the sherport qr-code will be generated by the function paymentGetSnippet
		// The login formular is only for demonstration purpose and is not functional
		$html.= '<h2>Anmelden</h2>
<p>Melden Sie sich mit Ihrem Qualle-Account an</p>
<form action="index.php" method="post">
<input type="hidden" name="step" value="1" />
<p class="newline clearfix">
<input class="clearfix" type="radio" name="ltype" id="ltype_old" value="old" /><label class="fette-zeile" for="ltype_old">Ich bin bereits Kunde</label></p>
<p class="einzug"><label for="email">Email:</label><input type="text" name="email" id="email" /><br />
<label for="password">Passwort:</label><input type="text" name="password" id="password" /><br />
<input type="submit" name="login" value="Anmelden" /></p>
<p class="newline clearfix">
<input type="radio" name="ltype" id="ltype_new" value="new" /><label class="fette-zeile" for="ltype_new">Ich bin ein neuer Kunde</label></p>
<p class="einzug"><input type="submit" name="register" value="Registrieren" /></p>
<p class="newline clearfix">
<input type="radio" name="ltype" id="ltype_sp" value="sp" /><label class="fette-zeile" for="ltype_sp">Mit Sherport anmelden und direkt bezahlen</label></p>
<p class="einzug">'.$sherport->paymentGetSnippet('index.php?step=5&amp;t='.$sherport->getToken()).'
</p>
';
		break;
	case 5:
		// Bestätigungsseite
		$html.= '<h2>Bestellbestätigung</h2>
<p>Möchten Sie die Bestellung an die aufgeführte Lieferadresse tätigen?</p>
<dl>
	<dt>Name</dt><dd>'.htmlspecialchars($_SESSION['userData']['address.shipping.name']).'</dd>
	<dt>Straße</dt><dd>'.htmlspecialchars($_SESSION['userData']['address.shipping.street']).'</dd>
	<dt>Ort</dt><dd>'.htmlspecialchars($_SESSION['userData']['address.shipping.postalCode'].' '.$_SESSION['userData']['address.shipping.city']).'</dd>
</dl>
<p class="einzug"><a href="index.php?step=6&pay=cancel">Bestellung abbrechen</a></p>
<p class="einzug"><a href="index.php?step=6&pay=confirm">Zahlungspflichtig bestellen</a></p>';
		//print_r($_SESSION);
		break;
	case 6:
		$sherport->importTokenArray($_SESSION['token']);
		if ($_GET['pay'] === 'confirm') {
			// User has confirmed the order on your website
			// Send confirmation to sherport
			if ($sherport->paymentConfirm()) {
				$html.= '<h2>Vielen Dank für Ihren Einkauf</h2>
<p>Vielen Dank für Ihren Einkauf bei "Die Qualle", dem führenden Onlineshop für Quallen-Fachbedarf.</p>
<p>Die von Ihnen bestellen Waren wurden per Sherport bezahlt und werden sofort zu Ihnen verschickt.</p>
';//.formatData($_SESSION['userData']);
			}
			else {
				// It went something wrong with confirmation
				// This can only be a transmission error
				// You should cancel the order here and show an error message to the user
			}
		}
		else {
			// User has canceled the order
			$sherport->paymentCancel();
			$html.= '<h2>Bestellung abgebrochen</h2>
<p>Schade das Sie es sich doch anders überlegt haben.</p>
<p>Die Bestellung wird nicht ausgeliefert und Ihr Konto wird nicht mit einer Zahlung belastet.</p>
';
		}
		// delete the stored token because we have used it
		unset($_SESSION['token']);
		break;
	default:
		// the page for step 1
		unset($_SESSION['token']);
		$html.= '<h1>Die Qualle</h1>
<p>Vielen Dank für Ihren Einkauf bei "Die Qualle".</p>
<h2>Ihr Warenkorb</h2>
<form action="index.php" method="post">
<input type="hidden" name="step" value="1" />
<table class="shopping-cart">
	<thead><tr><th>Anzahl</th><th>Produktbezeichnung</th><th>Stückpreis</th><th>Betrag</th></tr></thead>
	<tbody>
		<tr><td>2</td><td class="left">Qualle Furioso Red</td><td class="currency">11,89 €</td><td class="currency">23,78 €</td></tr>
		<tr><td>1</td><td class="left">Aquarium Plexiglas Rund</td><td class="currency">49,00 €</td><td class="currency">49,00 €</td></tr>
		<tr><td>5</td><td class="left">Quallo Deluxe 500gr Packung</td><td class="currency">3,49 €</td><td class="currency">17,45 €</td></tr>
		<tr class="stark"><td colspan="3">Warenwert</td><td class="sum currency">90,23 €</td></tr>
		<tr class="space"><td colspan="4"></td></tr>
		<tr class="stark"><td colspan="4" class="left">Versandart</td></tr>
		<tr><td colspan="3"><input type="radio" name="versand" id="versand_dhl" value="dhl" checked="checked" /><label class="kasse" for="versand_dhl">DHL</label></td><td>1,00 €</td></tr>
		<tr><td colspan="3"><input type="radio" name="versand" id="versand_hermes" value="hermes" /><label class="kasse" for="versand_hermes">Hermes</label></td><td>1,50 €</td></tr>
		<tr><td colspan="3"><input type="radio" name="versand" id="versand_nn" value="nn" /><label class="kasse" for="versand_nn">per Nachnahme</label></td><td>2,00 €</td></tr>
		<tr class="stark"><td colspan="3">Gesamtsumme</td><td class="sum currency">90,23 €</td></tr>
		<tr class="space"><td colspan="4"></td></tr>
		<tr class="space"><td colspan="4"><input class="center" type="submit" name="submit" value="weiter zur Kasse" /></td></tr>
	</tbody>
</table>
</form>
';
		break;
}

$template = file_get_contents('template.html');
$laufzeit = round(microtime(true) - $zeit_start, 4); // Laufzeit ermitteln
$footer = 'Seitenaufbau in '.$laufzeit.' Sekunden.';

$out = preg_replace_callback('/\$\{[A-Za-z_]+\}/', create_function(
	'$match',
	'return $GLOBALS[substr($match[0], 2, -1)];'
), $template);
echo $out;

// Utility function to format the userdata
function formatData($data) {
	$out = '<dl>';
	foreach ($data as $key => $value) {
		$out.= '<dt>'.$key.'</dt><dd>'.(is_array($value)? '': htmlspecialchars($value)).'</dd>';
	}
	return $out.'</dl>';
}
